### ISSUE TITLE
Lumbermill game

### ISSUE THREAD

**Issue by majoha** [bwimsett/COM2002-Team-42#7]
Couldn't contact you any other way but Dean the creator of Stationeers loves your game;

https://clips.twitch.tv/GrossFragileWalletGOWSkull

**Comment by bwimsett** [comment]
That's awesome, thanks for letting me know! I have a discord if you ever want to get in contact https://discord.gg/KX5rq78 :)

**Comment by majoha** [comment]
You're welcome. Looks a great game. Thanks for the Discord link.
Please feel free to delete this thread :D
